### ISSUE TITLE
Add Shelly Cloud Footer

### ISSUE THREAD

**Issue by bascht** [eurucamp/call4papers#55]
We're hosted on Shelly Cloud and they're really kind – so let's add a banner somewhere in the footer. I just had a chat with Sebastian from Shelly Cloud and we can add the logos to our repo:

* ![Transparent](https://shellycloud.com/assets/badge-transparent.png) 
or
* ![Solid](https://shellycloud.com/assets/badge.png)

**Comment by maser** [comment]
@bascht Is this what you had in mind?

welcome layout:

![screenshot from 2015-01-12 03 42 25](https://cloud.githubusercontent.com/assets/2545/5698393/28888910-9a0d-11e4-9856-c65c73e2c19d.png)

default layout:

![screenshot from 2015-01-12 03 42 47](https://cloud.githubusercontent.com/assets/2545/5698392/23060b98-9a0d-11e4-9efd-f5c4a640975a.png)

I could also put it into the actual footer by splitting the long text to two lines.

**Comment by bascht** [comment]
@maser Looks great! :+1: from me.
