### ISSUE TITLE
Send new_paper and error notifications to new address

### ISSUE THREAD

**Issue by maser** [eurucamp/call4papers#75]
Send them to cfp+new_paper@eurucamp.org respectively cfp+errors@eurucamp.org.

Hint: `config/application.yml`

**Comment by bitboxer** [comment]
I can create a new email address. Just let me know who should receive it and what the actual address should be.

**Comment by maser** [comment]
At least @moonglum and me would like to get the errors. Not sure who should get new paper notifications.

The addresses above would work for me.

**Comment by moonglum** [comment]
Yep, I don't know who wants to receive an email for each new paper. I don't think I want that :laughing: But sign me up for the errors :+1:

**Comment by skade** [comment]
I would recommend. People rarely take the time at logging in and checking the statistics every time.

**Comment by bascht** [comment]
If this includes *error notifications* as in stack traces: count me in. :)

**Comment by bitboxer** [comment]
I created both:

cfp-errors@eurucamp.org : me, @maser , @moonglum 
cfp-new-papers@eurucamp.org : me, @maser , @moonglum 

I would say we should not add too many to the cfp-new-paper to keep it as anonymous as possible.

**Comment by bitboxer** [comment]
@moonglum ping me if the errors are stack traces, i will add @bascht then :wink:

**Comment by moonglum** [comment]
Ok, great! Thanks!
