### ISSUE TITLE
Separate concept of Paper to Talk and Proposal

### ISSUE THREAD

**Issue by moonglum** [eurucamp/call4papers#77]
Instead of having papers, there should be talks and proposals. A user creates a talk (with information about the topic etc.) and one or more proposals to a subset of the three conferences. So a `Call` has many `Paper`s through `Proposal`s.

*This is required in order to be able to implement check boxes to choose for which conferences to propose*

**Comment by maser** [comment]
Unassigning myself in case somebody has the time to continue before I do.

**Comment by schultyy** [comment]
Just for me as clarification:
A paper contains the information to which conference the user wants to submit the proposal to?

**Comment by maser** [comment]
Strictly before we started changing everything:

A call (== conference) has many papers. A paper can only belong to one call.

**Comment by maser** [comment]
We show Proposal#created_at/updated_at in multiple places. Should show timestamps from Talk now.

**Comment by maser** [comment]
Completed in #98.

**Comment by maser** [comment]
#98 is merged. This has been open for a long time, so let’s just create new issues for bugs and further changes.
