### ISSUE TITLE
Adjust the proposal process to allow people to choose multiple conferences to propose to

### ISSUE THREAD

**Issue by moonglum** [eurucamp/call4papers#78]
Requires #77 

Instead of choosing the conference first, one clicks on "Create a proposal" and then has the chance to select one or more of the conference that they want to propose to.

**Comment by skade** [comment]
> he or she wants to propose to.

"they want" is elegant and neutral ;)

**Comment by moonglum** [comment]
Thanks :smile: Adjusted!

**Comment by maser** [comment]
Done in #98. It is not pretty, but I think making everything pretty should be done once the functionality is merged.

**Comment by maser** [comment]
#98 is merged. This has been open for a long time, so let’s just create new issues for bugs and further changes.
