### ISSUE TITLE
Cannot view proposal's details

### ISSUE THREAD

**Issue by schultyy** [eurucamp/call4papers#86]
I was playing around with the app to figure out some things thereby I bumped on this:

In the admin section I click on a talk's title to view the details. Then this exception occurs:

![screen shot 2015-03-18 at 14 20 24](https://cloud.githubusercontent.com/assets/235808/6710530/ad764e44-cd81-11e4-902a-bb59ed31e73c.png)

**Comment by schultyy** [comment]
I'm not sure if this is a bug or if I forgot to configure something.

**Comment by maser** [comment]
From your address bar I can tell you are running the branch of #83. So this is probably a bug in #83.

**Comment by schultyy** [comment]
This occured first in Martin's feature branch, that's why Proposal appears in there. But I also checked in master, same behavior there.

**Comment by maser** [comment]
Ack, might not be #83 then.

**Comment by maser** [comment]
Ahh, took me some time to figure out that `db:setup` is wrong and `db:create db:migrate db:seed` is right. Reproduced and working on it.
